package catalog

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const installerRevision = "67a506090e8ecf696190e0be55f865e3ce054d0e"

// The checked-in fixture is generated by this exact installer, not NativeBundle.
// scripts/test-installer-contract.sh also runs this test against a fresh export
// from the pinned Git tree. No runtime executable hashes are generated/trusted.
func TestPinnedInstallerContract(t *testing.T) {
	root := os.Getenv("BRIDGE_INSTALLER_FIXTURE")
	if root == "" {
		root = "testdata/installer"
	}
	revision, err := os.ReadFile(filepath.Join(root, "revision"))
	if err != nil || strings.TrimSpace(string(revision)) != installerRevision {
		t.Fatal("fixture must identify reviewed installer revision", err)
	}
	checkInstallerContract(t, root)
}

// Candidate checks supplement, never replace, the immutable known-good fixture.
func TestCandidateInstallerContract(t *testing.T) {
	root := os.Getenv("BRIDGE_INSTALLER_CANDIDATE")
	if root == "" {
		t.Skip("explicit candidate source export not supplied")
	}
	checkInstallerContract(t, root)
}

func checkInstallerContract(t *testing.T, root string) {
	t.Helper()
	if _, err := Import(root); err != nil {
		t.Fatal(err)
	}
	files := map[string][]byte{}
	var err error
	for _, path := range []string{"bundle.json", "qwen/settings.json", "dsh/settings.yaml", "hermes/config.yaml"} {
		files[path], err = os.ReadFile(filepath.Join(root, "bundle", path))
		if err != nil {
			t.Fatal(err)
		}
	}
	for _, h := range []string{"qwen", "dsh", "hermes"} {
		mode := "cli"
		if h == "dsh" {
			mode = "acp"
		}
		if _, err := VerifyNative(files, h, mode); err != nil {
			t.Fatal(h, err)
		}
	}
	var metadata BundleMetadata
	if err := json.Unmarshal(files["bundle.json"], &metadata); err != nil {
		t.Fatal(err)
	}
	if metadata.Sources["qwen"]["version"] != "0.23.2" || metadata.Sources["qwen"]["commit"] != "f56de980b316cd5410f067fbb62357481ebd66b8" {
		t.Fatal("wrong reviewed Qwen metadata")
	}
	metadata.Sources["qwen"]["version"] = "0.23.0"
	metadata.Sources["qwen"]["commit"] = "98a9c964158697dd5631d15a62174684ff7bbb53"
	files["bundle.json"], _ = json.Marshal(metadata)
	if _, err := VerifyNative(files, "qwen", "cli"); err == nil {
		t.Fatal("stale Qwen bundle accepted")
	}
	lock, err := os.ReadFile(filepath.Join(root, "versions.lock"))
	if err != nil {
		t.Fatal(err)
	}
	for _, pair := range [][2]string{{"QWEN_CODE_VERSION=0.23.2", "QWEN_CODE_VERSION=0.23.0"},
		{"f56de980b316cd5410f067fbb62357481ebd66b8", "98a9c964158697dd5631d15a62174684ff7bbb53"}} {
		dir := t.TempDir()
		changed := strings.Replace(string(lock), pair[0], pair[1], 1)
		if changed == string(lock) {
			t.Fatal("fixture did not contain expected pin")
		}
		if err := os.WriteFile(filepath.Join(dir, "versions.lock"), []byte(changed), 0600); err != nil {
			t.Fatal(err)
		}
		if _, err := Import(dir); err == nil || !strings.Contains(err.Error(), "harness contract drift") {
			t.Fatal("import drift refusal weakened", err)
		}
	}
}
